This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./kidiplom.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file kidiplom.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file kidiplom.acr....done (6 lines written, 0 warnings).
Output written in kidiplom.acr.
Transcript written in kidiplom.alg.
